default:
  image: node:14.18.1-alpine
  tags:
    - node

variables:
  npm_config_cache: "$CI_PROJECT_DIR/.npm"

.dependencies_cache:
  cache:
    key:
      files:
        - package-lock.json
    paths:
      - .npm
    policy: pull

stages:
  - setup
  - test

setup:
  stage: setup
  script:
    - apk add --no-cache git
    - apk add --no-cache python3 py3-pip
    - npm ci
  extends: .dependencies_cache
  cache:
    policy: pull-push
  artifacts:
    expire_in: 15m
    paths:
      - node_modules
  only:
    - merge_requests

test:
  stage: test
  script: npm run test
  only:
    - merge_requests
