default:
  image: node:14.18.1-alpine
  tags:
    - node

stages:
  - install
  - test

install:
  stage: install
  script:
    - npm install -q
  only:
    - merge_requests

test:
  stage: test
  script: npm run test
  only:
    - merge_requests